import { useEffect, useRef, useState } from 'react';
import { FileText, PanelLeftClose, Plus, Settings, X } from 'lucide-react';
import type { Note, NoteSummary } from '../shared/types';
type Heading={text:string;pos:number;level:number};
export function DocumentLibrary({notes,note,busy,onNote,onNew,onSettings,onClose}:{notes:NoteSummary[];note:Note|null;busy:boolean;onNote:(id:string)=>void;onNew:()=>void;onSettings:()=>void;onClose:()=>void}) {
 return <aside className="sidebar document-library" aria-label="文档库"><div className="brand"><img className="brand-mark" src="/brand/mark.svg" alt="" width="28" height="28"/><span>PaperMind</span><button className="icon-button" aria-label="收起文档库" onClick={onClose}><PanelLeftClose size={16}/></button></div><div className="library-label"><span>我的文档</span><button className="icon-button" aria-label="新建空白文档" disabled={busy} onClick={onNew}><Plus size={16}/></button></div><nav className="note-list">{notes.map(n=><button key={n.id} className={`note-item ${n.id===note?.id?'selected':''}`} disabled={busy} onClick={()=>onNote(n.id)}><FileText size={15}/><span>{n.title}</span></button>)}</nav><div className="sidebar-bottom"><button className="connection" onClick={onSettings}><Settings size={16}/><span>设置</span></button></div></aside>;
}
export function ArticleOutline({title,headings,onHeading,noteId}:{title:string;headings:Heading[];onHeading:(pos:number)=>void;noteId?:string}) {
 const [hover,setHover]=useState(false),[pinned,setPinned]=useState(false),[focus,setFocus]=useState(false),[active,setActive]=useState(0);const rail=useRef<HTMLButtonElement>(null);
 useEffect(()=>{setPinned(false);setHover(false);setActive(0);},[noteId]);
 useEffect(()=>{const area=document.querySelector('.reading-scroll');const update=()=>{const nodes=Array.from(document.querySelectorAll('.document-editor h1,.document-editor h2,.document-editor h3,.document-editor h4,.document-editor h5,.document-editor h6'));const edge=(area?.getBoundingClientRect().top||56)+150;let index=0;nodes.forEach((n,i)=>{if(n.getBoundingClientRect().top<=edge)index=i;});setActive(index);};update();area?.addEventListener('scroll',update,{passive:true});return()=>area?.removeEventListener('scroll',update);},[headings]);
 if(!headings.length)return null;const open=hover||pinned||focus;const min=Math.min(...headings.map(h=>h.level));
 return <div className="article-outline" onPointerEnter={e=>{if(e.pointerType==='mouse')setHover(true);}} onPointerLeave={()=>setHover(false)} onFocus={()=>setFocus(true)} onBlur={e=>{if(!e.currentTarget.contains(e.relatedTarget))setFocus(false);}} onKeyDown={e=>{if(e.key==='Escape'){setPinned(false);setHover(false);setFocus(false);rail.current?.blur();(document.querySelector('.document-title') as HTMLElement)?.focus();}}}>
  <button ref={rail} className="outline-strokes" aria-label="当前文章目录" aria-expanded={open} onClick={()=>setPinned(!pinned)}>{headings.map((h,i)=><span key={h.pos} className={i===active?'active':''} style={{width:Math.max(9,29-(h.level-min)*8)}}/>)}</button>
  {open&&<nav className="article-outline-popover" aria-label="当前文章章节"><header><strong>{title}</strong><button className="icon-button" aria-label="收起文章目录" onClick={()=>{setPinned(false);setHover(false);setFocus(false);(document.querySelector('.document-title') as HTMLElement)?.focus();}}><X size={15}/></button></header><p>目录</p><div>{headings.map((h,i)=><button key={h.pos} aria-current={active===i?'location':undefined} style={{paddingLeft:14+(h.level-min)*18}} onClick={()=>{onHeading(h.pos);setActive(i);}}>{h.text}</button>)}</div></nav>}
 </div>;
}
export function ArticleComments({note,busy,onThread,onClose}:{note:Note|null;busy:boolean;onThread:(id:string)=>void;onClose:()=>void}) {
 const [query,setQuery]=useState('');const threads=[...(note?.threads||[])].reverse().filter(t=>`${t.quote} ${t.messages.map(m=>m.text).join(' ')}`.toLowerCase().includes(query.toLowerCase()));
 return <aside className="article-comments" aria-label="当前文章批注"><header><strong>批注与讨论</strong><button className="icon-button" aria-label="收起批注列表" onClick={onClose}><X size={16}/></button></header><input className="comment-search" aria-label="搜索批注与讨论" placeholder="搜索原文或讨论…" value={query} onChange={e=>setQuery(e.target.value)}/>{threads.length?threads.map(t=><button className="comment-card" key={t.id} aria-label={`${t.quote.trim()} · ${t.messages.length} 条消息`} disabled={busy} onClick={()=>{onClose();onThread(t.id);}}><blockquote>{t.quote.trim()}</blockquote><p>{[...t.messages].reverse().find(m=>m.role==='assistant')?.text||t.messages.at(-1)?.text||'点击开始讨论'}</p><small>{t.detached?'原文已变化':t.proposals.at(-1)?.state==='applied'?'已融入正文':t.proposals.at(-1)?.state==='undone'?'写回已撤销':'原文讨论'} · {t.messages.length} 条消息</small></button>):<p className="nav-empty">{query?'没有匹配的讨论':'选中原文点「问 AI」，讨论会保存在这里。'}</p>}</aside>;
}
